apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: cloudflare-credentials
    creationPolicy: Owner
    template:
      data:
        credentials.json: |
          {"AccountTag":"{{ .ACCOUNT_TAG }}","TunnelSecret":"{{ .TUNNEL_SECRET }}","TunnelID":"{{ .TUNNEL_ID }}"}
        TUNNEL_ID: "{{ .TUNNEL_ID }}"
  data:
    - secretKey: ACCOUNT_TAG
      remoteRef:
        key: homelab/cloudflare
        property: ACCOUNT_TAG
    - secretKey: TUNNEL_ID
      remoteRef:
        key: homelab/cloudflare
        property: TUNNEL_ID
    - secretKey: TUNNEL_SECRET
      remoteRef:
        key: homelab/cloudflare
        property: TUNNEL_SECRET
