apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: cloudflare
spec:
  provider:
    vault:
      server: http://homelab-openbao.openbao.svc:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: cloudflare
          serviceAccountRef:
            name: cloudflare
