apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-config
  namespace: cloudflare
data:
  config.yml: |
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: argocd.morrisons.site
        service: http://argocd-server.argocd.svc.cluster.local:80
      - service: http_status:404
