apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-ingress.yaml") . | sha256sum }}
    spec:
      serviceAccountName: cloudflare
      containers:
        - name: cloudflare
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          command: ["cloudflared", "tunnel", "--config", "/etc/cloudflared/config.yml", "run", "$(TUNNEL_ID)"]
          env:
            - name: TUNNEL_ID
              valueFrom:
                secretKeyRef:
                  name: cloudflare-credentials
                  key: TUNNEL_ID
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: cloudflare-config
        - name: creds
          secret:
            secretName: cloudflare-credentials
            items:
              - key: credentials.json
                path: credentials.json
