apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: cloudflare-credentials
    creationPolicy: Owner
    template:
      data:
        credentials.json: |
          {"AccountTag":"{{ "{{" }} .ACCOUNT_TAG {{ "}}" }}","TunnelSecret":"{{ "{{" }} .TUNNEL_SECRET {{ "}}" }}","TunnelID":"{{ "{{" }} .TUNNEL_ID {{ "}}" }}"}
        TUNNEL_ID: "{{ "{{" }} .TUNNEL_ID {{ "}}" }}"
  data:
    - secretKey: ACCOUNT_TAG
      remoteRef:
        key: homelab/k8s-cloudflare/account-tag
        property: value
    - secretKey: TUNNEL_ID
      remoteRef:
        key: homelab/k8s-cloudflare/tunnel-id
        property: value
    - secretKey: TUNNEL_SECRET
      remoteRef:
        key: homelab/k8s-cloudflare/tunnel-secret
        property: value
